version: "3.9"

services:

  backend:
    container_name: meet_on_backend
    build: .
    ports:
      - "8000:8000"
    command: python core/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app/
